name: 'Start a testrun'
description: 'Start a testrun, uploading files as necessary'
inputs:
  app_arn:
    description: 'ARN of an existing upload to use as app'
    required: false
  project_arn:
    description: 'ARN of an existing device farm project'
    required: true
  device_pool_arn:
    description: 'ARN of an existing device pool'
    required: true
  test_type:
    description: 'Type of the test to schedule'
    required: true
  test_spec_arn:
    description: 'ARN of an existing test specification'
    required: false
  test_package_arn:
    description: 'ARN of an existing test package'
    required: false
  name:
    description: 'Name of the testrun'
    required: false
outputs:
  data:
    description: 'JSON data returned from the API'
  arn:
    description: 'The ARN of the newly created upload'
  parsing_result_url:
    description: 'The URL containing potential parsing errors'
  result_code:
    description: 'The result (pass/fail) of the test run'
  status:
    description: 'The status of the newly created upload'
runs:
  using: 'node16'
  main: 'dist/index.js'